name: Daily Retrain

on:
  schedule:
    - cron: '30 3 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  train-and-commit:
    runs-on: ubuntu-latest 
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/246240278810/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "github-ci-bq@delhi-weather-app-479422.iam.gserviceaccount.com"
          audience: "https://github.com/namannparashar/delhi-aqi-forecasting"

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch Data 
        run: python training/fetch_data.py

      - name: Train Model
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: python -m training.train

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add models/fcst_model.joblib
          git add models/X_future.csv
          git add models/metrics.json
          git add data/air_quality_latest.csv
          git add data/air_quality_current.csv
          
          # 5. Commit and Push to GitHub
          git commit -m "Auto-update model and data [skip ci]" || echo "No changes to commit"
          git push

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: namanparashar  
          HF_SPACE_NAME: delhi-aqi-forecast 
        run: python training/sync_to_hf.py